### ISSUE TITLE
Test Active Virtualenv

### ISSUE THREAD

**Issue by MortalCatalyst** [jmcantrell/vim-virtualenv#14]
Hi

I have installed your plugin, but it doe not appear to be running. I ammended the statusline in my vimrc to try and get some feedback from vim that it had indeed activate the env.

This is my statusline
set statusline=%<%f\ %h%m%r%{virtualenv#statusline()}%=%-14.(%l,%c%V%)\ %P

However after selecting my VirtualEnvActivate test2
I have nothing showing in my statusline, is there anyway to test to provide useful feedback?

**Comment by jmcantrell** [comment]
I'm going to assume that this is no longer a problem. Please reopen if not, and I'll explore further.
