### ISSUE TITLE
VirtualEnvActivate and othe commnads problem

### ISSUE THREAD

**Issue by vakosel** [jmcantrell/vim-virtualenv#19]
Hi~
i installed virtualenv with Bundle.
From commnad line  i used  $workon myproject. Activated it Then used vim from command line to open myproject.py .Both $WORKON_HOME and $RPOJECT_HOME variables set in
advance.when i type 
VirtualEnvList or wheatever command comes with plugin it is saying 
Not an editor commnad although i can use 
help virtualenv (opens the txt file)
Any idea?

**Comment by jmcantrell** [comment]
Any updates on this? I wasn't able to reproduce, and I've tested with vim and neovim (both compiled with python3).
