### ISSUE TITLE
PYTHONPATH mangling breaks `!supervisorctl`

### ISSUE THREAD

**Issue by blueyed** [jmcantrell/vim-virtualenv#20]
The change from https://github.com/jmcantrell/vim-virtualenv/pull/15 breaks invoking supervisorctl for me.

`:!supervisorctl update` fails as follows:

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/bin/supervisorctl", line 9, in <module>
    load_entry_point('supervisor==3.0', 'console_scripts', 'supervisorctl')()
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/home/user/.virtualenvs/project/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named supervisor.supervisorctl

shell returned 1

Press ENTER or type command to continue
```

This does not happen when I remove the addition of sys.path to PYTHONPATH.

The reason for this is that `/usr/lib/python2.7` gets added to PYTHONPATH. Removing it from the huge list (1394 chars), fixes it.

Apart from that, I think that copying the whole of sys.path into PYTHONPATH should be avoided.

I do not know which problem(s) @mtth tried to fix here, but it might just be necessary to install packages also inside of the virtualenv.

I will disable the PYTHONPATH mangling locally and see if I run into any problems.

@mtth: can you please elaborate on the intention behind this? After all the virtualenv activation scripts do not touch PYTHONPATH either.

**Comment by jmcantrell** [comment]
Is this still an issue?
