### ISSUE TITLE
Editing a file from PROJECT_HOME dir throws exeption

### ISSUE THREAD

**Issue by calind** [jmcantrell/vim-virtualenv#40]
If I define `PORJECT_HOME` environment variable and there is no activated virtualenv, doing `cd $PROJECT_HOME ; vim test.py` throws:

```
Error detected while processing function virtualenv#activate:
line   33:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/calind/dotfiles/vim/bundle/vim-virtualenv/autoload/pyvenv.py", line 9, in activate
    with open(activate) as f:
IOError: [Errno 2] No such file or directory: '/Users/calind/.virtualenvs/./bin/activate_this.py'
Press ENTER or type command to continue
```

The problem seems to be in this if branch https://github.com/jmcantrell/vim-virtualenv/blob/master/autoload/virtualenv.vim#L18-L25 because `fnamemodify(substitute(fn, pat, '', ''), ':h')` returns `.` when the current directory is `PORJECT_HOME`.

**Comment by jgosmann** [comment]
Having the same problem.

**Comment by jmcantrell** [comment]
@calind I tried the `fnamemodify` call with the current directory as `$PROJECT_HOME`, and I got the expected value. You seem to have `$PROJECT_HOME` set to a full path. The `expand('%:p')` should get the full path for the current file. Maybe you can add some steps to reproduce the function returning `.`?

**Comment by jgosmann** [comment]
I have set `$PROJECT_HOME` to a full path indeed.

The `substitute(...)` leaves me with the bare filename of the file I am editing (e.g., `test.py`). The `fnamemodify(..., ':h')` converts it then to `.`.

**Comment by jmcantrell** [comment]
Oh, is the path something like `$PROJECT_HOME/test.py`?

**Comment by jgosmann** [comment]
Yes.

**Comment by jmcantrell** [comment]
Just curious if this is still an issue? I'm still unable to reproduce it.
