### ISSUE TITLE
Airline support doesn't work

### ISSUE THREAD

**Issue by tommyc38** [jmcantrell/vim-virtualenv#48]
I followed the directions in airline by putting the following in my vimrc file:

let g:airline#extensions#virtualenv#enabled = 1

but it doesn't update my statusline like it should.  I only managed to get it to work when I add this:

let g:airline_section_x = airline#section#create('%{virtualenv#statusline()}')

However, it no longer adds filetypes like I want it to.  Can you please tell me what I am doing wrong?

**Comment by chrisbra** [comment]
Please see https://github.com/vim-airline/vim-airline/pull/930
However vim-virtualenv needs an update as well.

**Comment by jmcantrell** [comment]
Sorry I'm late to this. I don't use airline, personally, but I'm happy to add functionality to allow it to work correctly. I can get what I need from that thread?

**Comment by chrisbra** [comment]
Should be pretty simple, since vim-airline/vim-airline#930 has been merged. See here please:
https://github.com/vim-airline/vim-airline/issues/511#issuecomment-173335314

**Comment by oryband** [comment]
:+1:
