### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by sassanh** [jmcantrell/vim-virtualenv#54]
Is it possible to make it lazyload on vim startup using features vim-plug or maybe other plugin managers provide?
My Vim takes 1.3 sec to startup with this plugin activated, when I deactivate it, it startups in .8 sec.

**Comment by rachmadaniHaryono** [comment]
here is my setting for vim-plug

    Plug 'jmcantrell/vim-virtualenv', {'for': ['python', 'python3']}

taken little bit from here https://github.com/lambdalisue/vim-pyenv

**Comment by sassanh** [comment]
Thanks, it works for me.
