### ISSUE TITLE
vim-virtualEnv with MacVim seems not working

### ISSUE THREAD

**Issue by arnaudlamy** [jmcantrell/vim-virtualenv#55]
Hi,

I tried to load my env first then launch mvim, export VIRTUAL_ENV=~/src/my_project/env and then launch mvim without any result. Everytime there's no env activated or in the list. Anyone is using it with MacVim ?

MacVim version: - Vim patch 7.4.2196

Thanks for your help !

**Comment by cmcginty** [comment]
I can confirm this. MacVim 8.0.124

**Comment by iovis9** [comment]
I just discovered it even prevents my MacVim from launching.

**Comment by cmcginty** [comment]
This may be an issue with the virtualenv tooling on Mac. I use `pyenv-virtualenv` but it looks like this plugin needs a script called `activate_this.py`. This must be part of another virtualenv tool since I get `pyenv: activate_this.py: command not found` when trying to run it.

**Comment by jmcantrell** [comment]
I use the `virtualenv` command that's available from `pip install virtualenv`. I'm not sure what pyenv is doing differently. If you create an environment with `virtualenv env`, then `activate_this.py` will be at `env/bin/activate_this.py`. I assume you're using MacVim, as well? Have you tried it with console vim or neovim? I'll try this out on my macbook. Do you have some steps I can do to reproduce it?

**Comment by cmcginty** [comment]
What is `activate_this.py` doing? I'm sure there is a way to replicate it for my setup.

**Comment by michaelcoyote** [comment]
Was this ever addressed?  I'm seeing this on my setup as well and it's mid-2019.

**Comment by jmcantrell** [comment]
I don't use MacVim, and don't know enough about how it differs from vim/nvim/gvim. If someone can give me steps to reproduce it, I'll look into this.
