### ISSUE TITLE
How to install vim-virtualenv in linux?

### ISSUE THREAD

**Issue by elhackerlibre** [jmcantrell/vim-virtualenv#58]
I want to install the plugin
But I do not see that explain the steps or in which route should clone the plugin?
This plugin depends on Pathogen
I already have it installed and configured in my .vimrc

**Comment by jmcantrell** [comment]
It doesn't depend on pathogen, but the layout is compatible with it, and likely other plugin managers.

You could install it in a pathogen-compatible way (not including pathogen configuration):

    mkdir -p ~/.vim/bundle
    git clone https://github.com/jmcantrell/vim-virtualenv.git ~/.vim/bundle/virtualenv

Conveniently, the same layout used for most plugin managers is just the standard vim plugin layout, so you could manually install it by putting the files directly in your vim folder:

    cd `mktemp -d`
    curl -LO https://github.com/jmcantrell/vim-virtualenv/archive/master.zip
    unzip master.zip
    cp vim-virtualenv-master/* ~/.vim

I wouldn't recommend the manual method as it's a bit difficult to uninstall or upgrade, but it does illustrate how it doesn't depend on anything.
