### ISSUE TITLE
Doesn't update $PATH under neovim

### ISSUE THREAD

**Issue by tpict** [jmcantrell/vim-virtualenv#59]
Running NVIM v0.2.0-485-g81525dc:

- Create virtualenv: `python3 -m venv $HOME/.virtualenvs/myvenv`
- Open Neovim
- `:VirtualEnvActivate myvenv`
- `echo $PATH` output doesn't include the `myvenv/bin/` directory
- `:python import sys; print(sys.path)` returns `['/Users/tpict/.virtualenvs/myvenv/lib/python2.7/site-packages', ...`

that folder doesn't exist - Python 2.7 is the default installation on OS X, and the virtualenv uses 3.6

**Comment by tpict** [comment]
Could it be that Neovim executes `python`/`python3` commands in a separate shell? e.g. if `has('nvim')` we need to call `let $PATH...`

**Comment by jmcantrell** [comment]
I apologize for not responding to this sooner. It looks like #69 should fix this. Please re-open if not.
