### ISSUE TITLE
DeprecationWarning: imp module is deprecated in favor of importlib

### ISSUE THREAD

**Issue by diepenbrock** [jmcantrell/vim-virtualenv#63]
I am experiencing a DeprecationWarning - after installing the vim-virtualenv bundle via Vundle - which is raised each time I open a file via vim - whether or not I have a virtualenv open. When I remove the bundle, everything words normal. 

Here's the error:
`Error detected while processing /Users/plutonium/.vim/bundle/vim-virtualenv/autoload/vir
tualenv.vim:
line    2:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of imp
ortlib; see the module's documentation for alternative uses`

I found a seemingly similar issue with  [https://github.com/ARM-DOE/pyart/pull/675](ARM-DOE/pyart), but it's from August 2017. Not sure how much help it would be. 

Not sure if it's my configuration or cwd. I do have vim and python installed via homebrew, and virtualenvwrapper inside my global pip3. 

Anyone else ran into this issue?

Versions:
Python3 - 3.7.0
Vim - 8.1 (inside homebrew)

**Comment by garettmd** [comment]
I'm using 3.7.0 on my system as well. If you run `import imp` under any version under 3.7 it works fine, but I guess the imp module is deprecated in 3.7.

**Comment by diepenbrock** [comment]
@garettmd I suppose one could temporarily convert  back to a previous version. Since this plugin seems to be stale (viewing the last commit), I figured I would continue to `workon venv` before opening vim. The only caveat is doing it for every pane and window that's open, since active venvs don't roll over to the next pane or window.

**Comment by garettmd** [comment]
I just noticed that my issue is different from yours. Mine only occurs when I have a virtualenv activated. I assume that this issue might be easy to fix, but I haven't had enough time to look into the code

**Comment by jmcantrell** [comment]
Apologies for the late reply. I'm not sure what's going on with this, but I'm not sure why this plugin would be complaining about trying to import an `imp` module. I can't recall ever using that nor find any reference to it. I'm going to close this, as it's been a long time, and I'm not sure it's relevant still. Feel free to reopen if you still would like it looked into.
