### ISSUE TITLE
Image no longer available

### ISSUE THREAD

**Issue by abe-101** [jmcantrell/vim-virtualenv#70]
The link to the image is no longer available

https://github.com/jmcantrell/vim-virtualenv/blob/b1150223cd876f155ed7a3b2e285ed33f6f93873/README.mkd?plain=1#L29

Showing this:

 ![tab-completion](http://i.imgur.com/1ZGrM.png "Tab Completion")

**Comment by jmcantrell** [comment]
Thanks for letting me know. I've removed the image references. I may add back some new images later.
